
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Debug Build Output
        run: |
          echo "Listing build output directory:"
          ls -la dist/
          echo "Content of index.html (first 50 lines):"
          head -50 dist/index.html || echo "index.html not found"
          echo "Checking if assets exist:"
          ls -la dist/assets/ || echo "No assets directory found"
          echo "Checking for JavaScript files:"
          find dist -name "*.js" -type f || echo "No JS files found"
          echo "Checking for CSS files:"
          find dist -name "*.css" -type f || echo "No CSS files found"

      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      - name: Copy 404.html to build folder
        run: cp 404.html dist/

      - name: Verify deployment files
        run: |
          echo "Final verification of dist folder:"
          ls -la dist/
          echo "Checking if 404.html exists:"
          ls -la dist/404.html
          echo "Checking if .nojekyll exists:"
          ls -la dist/.nojekyll
          echo "Total files in dist:"
          find dist -type f | wc -l

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          single-commit: true

      - name: Output deployment info
        run: |
          echo "Deployment completed!"
          echo "Your site should be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          echo "If the site shows blank, check the browser console for errors"
          echo "Repository: ${{ github.repository }}"
          echo "Repository name: ${{ github.event.repository.name }}"
